services:
  - type: web
    name: omnion-cloud-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: credenciales_omnion.json
